# 01 Extraction

Use this notebook to load the raw dataset, inspect its structure, and confirm that the source is suitable for the project.

In [16]:
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd().resolve().parent if Path.cwd().resolve().name == 'notebooks' else Path.cwd().resolve()

In [17]:
ASTROID_CLOSE_DATA = PROJECT_ROOT / 'asteroid_close_approaches_2015_2035.csv'

astroid_close_data = pd.read_csv(ASTROID_CLOSE_DATA)

astroid_close_data.head()

,designation,full_name,close_approach_date,distance_au,dist_km,dist_lunar,distance_min_au,distance_max_au,velocity_km_s,v_rel_kmh,velocity_infinity_km_s,absolute_magnitude,is_future
0,2022 AP1,(2022 AP1),2015-01-01 00:27,0.045100,6746806.0,17.55,0.013778,0.076571,11.891749,42810.0,11.886780,28.39,False
1,2015 AE45,(2015 AE45),2015-01-02 15:56,0.048239,7216474.0,18.77,0.048220,0.048258,7.065686,25436.0,7.057864,25.30,False
2,613286,613286 (2005 YQ96),2015-01-02 21:46,0.026522,3967664.0,10.32,0.026522,0.026522,12.703378,45732.0,12.695467,20.63,False
3,2014 YQ34,(2014 YQ34),2015-01-03 13:29,0.079692,11921722.0,31.01,0.078275,0.081108,24.982094,89936.0,24.980756,24.16,False
4,2014 YE42,(2014 YE42),2015-01-03 15:00,0.010995,1644896.0,4.28,0.010971,0.011020,13.998882,50396.0,13.981561,23.40,False

In [18]:
NEAR_EARTH_ASTEROIDS_DATA = PROJECT_ROOT / 'near_earth_asteroids_2025.csv'

near_earth_asteroids_data = pd.read_csv(NEAR_EARTH_ASTEROIDS_DATA)

near_earth_asteroids_data.head()

/tmp/ipykernel_18619/3042439253.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  near_earth_asteroids_data = pd.read_csv(NEAR_EARTH_ASTEROIDS_DATA)

,spkid,full_name,pdes,name,pha,H,diameter_km,diameter_m,diameter_is_estimated,size_category,...,per_y,moid_au,moid_km,moid_lunar_distances,n,condition_code,first_obs,last_obs,data_arc,data_arc_years
0,20000433,433 Eros (A898 PA),433,Eros,False,10.39,16.84000,16840.0,False,Large (>1 km) — City killer+,...,1.76,0.1480,22140485.0,57.60,0.5598,0.0,1893-10-29,2021-05-13,46582.0,127.53
1,20000719,719 Albert (A911 TB),719,Albert,False,15.59,2.70683,2706.8,True,Large (>1 km) — City killer+,...,4.28,0.2010,30069172.0,78.22,0.2302,0.0,1911-10-04,2026-03-20,41806.0,114.46
2,20000887,887 Alinda (A918 AA),887,Alinda,False,13.82,4.20000,4200.0,False,Large (>1 km) — City killer+,...,3.89,0.0797,11922950.0,31.02,0.2533,0.0,1918-02-09,2025-08-27,39281.0,107.55
3,20001036,1036 Ganymed (A924 UB),1036,Ganymed,False,9.17,37.67500,37675.0,False,Large (>1 km) — City killer+,...,4.35,0.3430,51312070.0,133.49,0.2266,0.0,1924-10-23,2026-03-22,37040.0,101.41
4,20001221,1221 Amor (1932 EA1),1221,Amor,False,17.37,1.00000,1000.0,False,Large (>1 km) — City killer+,...,2.66,0.1080,16156570.0,42.03,0.3705,0.0,1932-03-12,2025-02-19,33947.0,92.94

In [19]:
print(astroid_close_data.shape)

astroid_close_data.info()

(27430, 13)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27430 entries, 0 to 27429
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   designation             27430 non-null  object
 1   full_name               27430 non-null  object
 2   close_approach_date     27430 non-null  object
 3   distance_au             27430 non-null  float64
 4   dist_km                 27430 non-null  float64
 5   dist_lunar              27430 non-null  float64
 6   distance_min_au         27430 non-null  float64
 7   distance_max_au         27430 non-null  float64
 8   velocity_km_s           27430 non-null  float64
 9   v_rel_kmh               27430 non-null  float64
 10  velocity_infinity_km_s  27413 non-null  float64
 11  absolute_magnitude      27422 non-null  float64
 12  is_future               27430 non-null  bool
dtypes: bool(1), float64(9), object(3)
memory usage: 2.5+ MB

In [20]:
print(near_earth_asteroids_data.shape)

near_earth_asteroids_data.info()

(41281, 29)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41281 entries, 0 to 41280
Data columns (total 29 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   spkid                  41281 non-null  int64
 1   full_name              41281 non-null  object
 2   pdes                   41281 non-null  object
 3   name                   182 non-null    object
 4   pha                    41281 non-null  bool
 5   H                      41279 non-null  float64
 6   diameter_km            41281 non-null  float64
 7   diameter_m             41281 non-null  float64
 8   diameter_is_estimated  41281 non-null  bool
 9   size_category          41281 non-null  object
 10  albedo                 1204 non-null   float64
 11  rot_per                2181 non-null   float64
 12  class                  41281 non-null  object
 13  e                      41281 non-null  float64
 14  a                      41281 non-null  float64
 15  i                      41281 non-null  float64
 16  q                      41281 non-null  float64
 17  ad                     41281 non-null  float64
 18  per                    41281 non-null  float64
 19  per_y                  41281 non-null  float64
 20  moid_au                41150 non-null  float64
 21  moid_km                41150 non-null  float64
 22  moid_lunar_distances   41150 non-null  float64
 23  n                      41281 non-null  float64
 24  condition_code         41279 non-null  float64
 25  first_obs              41280 non-null  object
 26  last_obs               41281 non-null  object
 27  data_arc               40875 non-null  float64
 28  data_arc_years         40875 non-null  float64
dtypes: bool(2), float64(19), int64(1), object(7)
memory usage: 8.6+ MB